# Generated by Django 4.2 on 2023-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0006_remove_photopost_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=500, verbose_name="コメント1"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="投稿日時"),
        ),
    ]
