# Generated by Django 4.2 on 2023-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0009_rename_target_comment_photo_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="photo_post", new_name="target",
        ),
        migrations.RemoveField(model_name="comment", name="content",),
        migrations.AddField(
            model_name="comment",
            name="message",
            field=models.TextField(
                default="コメントはこちら", max_length=500, verbose_name="本文"
            ),
        ),
    ]
